language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"
script:
## Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t reverseproxy ./reverseproxy
  - docker build -t udagram-frontend ./udagram-frontend
## Tagging
  - docker tag udagram-api-feed thanh1999/udagram-api-feed:v1
  - docker tag udagram-api-user thanh1999/udagram-api-user:v1
  - docker tag reverseproxy thanh1999/reverseproxy:v1
  - docker tag udagram-frontend thanh1999/udagram-frontend:v1
```bash
after_success:
## Push
## Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push thanh1999/udagram-api-feed:v1
  - docker push thanh1999/udagram-api-user:v1
  - docker push thanh1999/reverseproxy:v1
  - docker push thanh1999/udagram-frontend:v1